### PR TITLE
Added junit test that fails. Possible typo in tested code.

### PR DESCRIPTION
**Pull request by MockerTim**
Hi, Sander. It seems, there is a typo in the tested code. The MessageIdGeneratorTest. testCreateContentId() test fails.

### CODE REVIEW

**Comment by sfieten** [comment]
Hi Timur, 
you're completely right about the typo!  
To get the part before the '@' it should of course read `msgId.substring(0, i)`.  I have just corrected this and now the test runs fine.

**Comment by sfieten** [comment]
Now that we have the package `org.holodeckb2b.testhelpers` in both the Common and Core module I am wondering if these should be rename to `org.holodeckb2b.**«modulename»**.testhelpers` to clearly distinguish between the different implementations? 

If you agree with this can you please make this change?

**Comment by MockerTim** [comment]
Sure. Done.

**Comment by MockerTim** [comment]
Hi Sander,
Have a look at my last commit, please. It seems that there is some bug in UserMessage.

**Comment by MockerTim** [comment]
I've fixed the typo. Tests pass now.

**Comment by MockerTim** [comment]
Fixed another typo. Just to make the test pass. We'll need to add more null checks.

**Comment by sfieten** [comment]
Hi Timur,
to be able to build the project on Netbeans I had to add the persistency module as a test dependency to the Core. I also noticed that for the tests of the Core module the database is now created in the project root folder. I therefore update the .gitignore file to ignore the db directory, so it will not be included in versioning.

**Comment by MockerTim** [comment]
Hi Sander,
thank you for the information. I've merged your changes successfully.

Regards,
Timur Shakuov

2017-02-03 11:53 GMT+03:00 Sander Fieten <notifications@github.com>:

**Pull request merged**
